package ru.minebot.cloverserver;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Presets {
    public static final List<Map<String, Object>> maps = new ArrayList<>();

    static {
        Map<String, Object> m1 = new HashMap<>();
        List<String> l1 = new ArrayList<>(){{
            add("A-Boy-Falls-in-Love-with-a-Girl");
            add("Anon-");
            add("Berserk");
            add("Bleach");
            add("Bobobo-bo-Bo-");
            add("Code-Geass");
            add("Dragon-Ball-Z");
            add("Dragon-Ball");
            add("Fate");
            add("Goblin-Slayer");
            add("GochiUsa");
            add("Gundam");
            add("Hyper-Dimension-Neptunia");
            add("Initial-D");
            add("Jojo-s-Bizarre-Adventure-2");
            add("Made-in-Abyss");
            add("Monogatari");
            add("My-Hero-Academia");
            add("Naruto-Might-be-too-long");
            add("Naruto");
            add("One-Punch-Man");
            add("Phoenix-Wright");
            add("Pressure");
            add("Shield-Hero");
            add("Slayers");
            add("Touhou-2");
            add("Touhou-3");
            add("Umineko");
        }};
        m1.put("theme", "Anime");
        m1.put("list", l1);

        Map<String, Object> m2 = new HashMap<>();
        List<String> l2 = new ArrayList<>(){{
            add("Based-Lord-of-the-Mysteries-fags");
            add("Death-Knight-DnD");
            add("Harry-Potter-2");
            add("Harry-Potter-3");
            add("Harry-Potter");
            add("Moby-Dick-Music-Blood-and-Thunder");
            add("Orion-s-Arm-Universe");
            add("SCP");
        }};
        m2.put("theme", "Books");
        m2.put("list", l2);

        Map<String, Object> m3 = new HashMap<>();
        List<String> l3 = new ArrayList<>(){{
            add("GNU+Linux");
            add("kornilov");
        }};
        m3.put("theme", "cloveranon-prompts");
        m3.put("list", l3);

        Map<String, Object> m4 = new HashMap<>();
        List<String> l4 = new ArrayList<>(){{
            add("AltHis-WWII-Meme");
            add("Music-Take-Me-Away");
            add("Wrestling-Modern");
        }};
        m4.put("theme", "Existing-Media");
        m4.put("list", l4);

        Map<String, Object> m5 = new HashMap<>();
        List<String> l5 = new ArrayList<>(){{
            add("Anon-s-Original-Setting-High-Fantasy");
            add("Anon-Vampire-Loli-Daughteru");
            add("Anon-Wizard-Kickflips");
            add("Boyfriend-Quest-Sir-Theo");
            add("Dark-Fantasy");
            add("Dragon-Hell-Vore");
            add("Dragon");
            add("Elf-Fantasy");
            add("Eliminate-God");
            add("Fantasy-Companionship");
            add("Fantasy-Dwarf-Elf");
            add("Fantasy-Elf-Dwarf");
            add("Fantasy-Original-Goblin");
            add("Fantasy-Original");
            add("Fantasy-Purification-Corruption");
            add("Fantasy-Tactical");
            add("Fantasy-Wizard-Autism-Rat-kin");
            add("Fantasy-Wizard");
            add("Feudal-Japan-F-Fantasy-Ninja");
            add("Fungi-Wizard-Evil-Transformation");
            add("Giant-Farming");
            add("Goody-Two-Shoes-Knight-slaying-Evil");
            add("Gunslinger-Dark-Fantasy-Western");
            add("Hard-Men-Making-Hard-Choices-whilst-Hard");
            add("Isekai");
            add("Knight-Dark-Fantasy");
            add("Larion-Demon-Slave");
            add("Lazy-Power-Fantasy-Prompt");
            add("Lich-Fantasy");
            add("Magician-Competition");
            add("Martial-Arts");
            add("Modern-Weaboo-Strategy");
            add("Monster-Hunting-Fantasy");
            add("Multiverse");
            add("Muscle-Wizard-Muscleman");
            add("Potions-are-Too-Strong-2");
            add("Potions-are-Too-Strong");
            add("Power-Fantasy-God");
            add("Probably-belongs-in-Just-Porn");
            add("Revolution-Betrayal-Larion-NTR");
            add("Santa-Claus-2");
            add("Santa-Claus-3");
            add("Santa-Claus");
            add("Slaves");
            add("Spice-and-Wolf");
            add("You-are-a-knight-in-the-kingdo");
            add("You-are-Dave-the-angriest-wiz");
        }};
        m5.put("theme", "Fantasy");
        m5.put("list", l5);

        Map<String, Object> m6 = new HashMap<>();
        List<String> l6 = new ArrayList<>(){{
            add("Ace-Combat");
            add("Bionicle");
            add("Blade-Runner");
            add("Bloodborne");
            add("Borderlands");
            add("Cyberpunk-2020");
            add("Danganronpa");
            add("Dark-Souls-2");
            add("Dark-Souls");
            add("Deltarune");
            add("Deus-Ex");
            add("Devil-May-Cry-DMC");
            add("Doom-2");
            add("Doom-3");
            add("Doom");
            add("Dwarf-Fortress");
            add("E-Y-E-Divine-Cybermancy");
            add("EDF-Earth-Defense-Force");
            add("Escape-from-Tarkov");
            add("Faith");
            add("Fate-Stay");
            add("FEAR");
            add("Final-Fantasy-2");
            add("Final-Fantasy");
            add("Fire-Emblem");
            add("God-of-War");
            add("Half-Life");
            add("Halo-Reach");
            add("Hatred");
            add("Kenshi");
            add("Life-is-Strange");
            add("Metal-Gear-MGS");
            add("Morrowind-Elder-Scrolls");
            add("Nier-Automata");
            add("Overwatch");
            add("Papers-Please");
            add("Peasant-s-Quest");
            add("Pokemon-2");
            add("Pokemon-3");
            add("Pokemon");
            add("Postal-2");
            add("Postal-3");
            add("Postal");
            add("Recettear");
            add("Red-Dead-Redemption");
            add("Resident-Evil-3");
            add("Secret-Song-of-King-Wulfharth-War-Strategy-TES");
            add("Sengoku-Rance");
            add("Shadowrun-v2");
            add("Shadowrun");
            add("Skyrim-Elder-Scrolls-2");
            add("Skyrim-Elder-Scrolls");
            add("System-Shock");
            add("Tales-of-Maj-Eyal");
            add("Touhou");
            add("Undertale-2");
            add("Undertale");
            add("Witcher");
            add("Yakuza");
        }};
        m6.put("theme", "Games");
        m6.put("list", l6);

        Map<String, Object> m7 = new HashMap<>();
        List<String> l7 = new ArrayList<>(){{
            add("Anti-Semitic");
            add("Biblical");
            add("Big-Iron-Western");
            add("Colonization");
            add("Columbine");
            add("Epic-of-Gilgamesh");
            add("Feudal-Japan");
            add("Gladiator-Fights-in-Rome");
            add("Grug");
            add("Hitler-Card-Games");
            add("Japan-Oda-Nobunaga-Isekai-RTS");
            add("Mexican-Revolution");
            add("Navy-Seal-Hitler");
            add("Odyssey-Greek-Mythology");
            add("Purify-the-Unclean");
            add("Vietnam-War-2");
            add("Vietnam-War-3");
            add("Vietnam-War");
            add("Viking");
            add("Western-Indian");
            add("White-House-Battle");
            add("WW2-Soviet");
            add("WWII-2");
            add("WWII-Hitler");
            add("WWII-Soviet-Cold-War");
            add("WWII-Tanks-Germany");
            add("WWII");
            add("You-are-a-male-citizen-of-the");
            add("You-are-Abdul-You-are-an-outl");
            add("You-are-the-chief-bodyguard-of");
        }};
        m7.put("theme", "Historical-Adventures");
        m7.put("list", l7);

        Map<String, Object> m8 = new HashMap<>();
        List<String> l8 = new ArrayList<>(){{
            add("French-Shit");
            add("gsg-vic2-Historical");
            add("Indian-Wars-2");
            add("Indian-Wars");
            add("Jojo-s-Bizarre-Adventure");
            add("Roman-Republic");
            add("WWI-2");
            add("WWI");
            add("WWII-3");
            add("WWII-4");
        }};
        m8.put("theme", "Historical-RTS");
        m8.put("list", l8);

        Map<String, Object> m9 = new HashMap<>();
        List<String> l9 = new ArrayList<>(){{
            add("Amazon-Futa-M-F");
            add("Anon-Breeding-Pokemon-Eggs-Beast");
            add("Anon-Digimon-M-F-Furry");
            add("Anon-Elf-Loli-Marriage-M-F");
            add("Anon-Feet-Sub-M-F");
            add("Anon-Futa-M-F");
            add("Anon-Futa-PubUse-Sub-Slave-M-F");
            add("Anon-Futa-Sissy-Meme-M-F");
            add("Anon-Lilly-Vanilla-M-F");
            add("Anon-M-M-Minotaur-Handholding-Fantasy");
            add("Anon-Meme-Coomer-M");
            add("Anon-Milk-Size-Vore-Beast");
            add("Anon-Mother-Son-Incest-Futa-M-F");
            add("Anon-Multi-M-M");
            add("Anon-NTR-M-F");
            add("Anon-Original-Centaur-Breeding-DubCon-Amazon-Bondage-M-F");
            add("Anon-Piss-Kemono");
            add("Anon-Shota-Loli-M-F-Piss-Teasing");
            add("Anon-Shota-Sissy-Futa-Sub-Mother-Son-Loli");
            add("Anon-TF");
            add("Anon-Tomboy-Vanilla-M-F");
            add("Breast-Expansion-F");
            add("Breast-Expansion-Milk");
            add("Breast-Expansion");
            add("Catgirl-Lilly-Anon-NTR-Multi-M-F");
            add("Catgirl-Lilly-Dom-M-F");
            add("Catgirl-Lilly-NTR-Anon-Multi-M-F");
            add("Catgirl-Lilly-Rape-Loli-Multi-F-M");
            add("Catgirl-Lilly-Rape-M-F-Bondage");
            add("Catgirl-Lilly-Rape");
            add("Catgirl-Lilly-Sub-F-F");
            add("Catgirl-Lilly-Sub-F-M");
            add("Cloning-Selfcest-M-M");
            add("Coomer-Loli-M-F");
            add("Cunny-Loli-M-F");
            add("Degen-Extremely-Lewd-Corruption-M");
            add("Dom-F-This-is-porn-right");
            add("Dom-M-M");
            add("Dracula-M-F-Vampire");
            add("Dragon-Dom-2");
            add("Dragon-Dom-3");
            add("Dragon-Dom");
            add("Dragon-Kobold-M-M-Dom");
            add("Dragon-Kobold-M-M-Multi");
            add("Dragon-Kobold-M-M-Size");
            add("Dragon-Kobold-M-M");
            add("Dragon-Kobold-Rape-M-M-2");
            add("Dragon-Kobold-Rape-M-M");
            add("Dragon-Kobold-Sub-M-M");
            add("Dragon-M-F-Fantasy-Feral");
            add("Dragon-M");
            add("Dragon-Rape-M-F-Furry");
            add("Dragon-TF-M-M");
            add("Elf-Dom-Master");
            add("Elf-Orc-Rape-Size");
            add("Elf-Rape-Horse-Breeding-F-M");
            add("Elf-Rape-Loli-Size");
            add("Elf-Shota-Horse-Sub");
            add("Elf-Shota-Mommy-M-F-Size");
            add("Elf-Size-Orc-F-M");
            add("Elf-Warcraft-Rape-Beast");
            add("F-F");
            add("F-M-Loli-Abuse-Rape-Reminds-me-of-DoL-ugh");
            add("Fairy-Vore-Size-F-F");
            add("Fantasy-Vanilla-M-F-2");
            add("Fantasy-Vanilla-M-F");
            add("Fat-Feed-M-F");
            add("FiM-NTR");
            add("Final-Fantasy-Lilly-Catgirl-F-M");
            add("Fox-Rape-Furry");
            add("Free-Cities-Master-Breeding");
            add("Furry-M-M");
            add("Furry-Rape-Anon-M-F");
            add("Furry-Sub-M-F");
            add("Futa-F-F");
            add("Futa-Rape-Sub-F-F-Lilly");
            add("Genderbending-F-M");
            add("Ghost-M");
            add("Goblin-Rape");
            add("Goth-F-M-Humiliation");
            add("Grim-s-Fairy-Tales-Vore-Rape-Furry-Loli-M-F");
            add("Grug-Shota-Sub");
            add("Halo-M-F");
            add("Hell");
            add("Horse-M-F-Beast");
            add("Humiliation-F");
            add("Humiliation");
            add("Incest-Loli-Shota-M-F-Twin");
            add("Incest-M-F-Tomboy");
            add("Incest-M-F");
            add("Incest-Shota-M-M");
            add("Katia-TES-Khajit-Catgirl");
            add("Kemono-Friends-Vore-Rape-Beast");
            add("Kobold-Orc-Size-M");
            add("Kobold-Size-Furry-Slave-F-M");
            add("Lilly-Bondage-Multi-F");
            add("Lilly-F-F-Incest-Loli");
            add("Loli-Incest-M-F");
            add("Loli-M-F");
            add("Loli-Orc-Spanking");
            add("M-F-DubCon");
            add("M-F-Kemono-Monstergirl");
            add("M-F-M-M-Loli-Shota-Demon-Sub-Bondage");
            add("M-F-Rape");
            add("M-M-Incest-Shota-Cross-dressing-Sissy");
            add("Madoka-Magica-F-F-2");
            add("Madoka-Magica-F-F");
            add("Magical-Girl-F-M-Tentacles");
            add("Magical-Girl-Madoka-Magica-F-F");
            add("Master-Slave-Breathplay-Snuff");
            add("Monster-Girl-Dragon-Ocean-Size-M-F");
            add("Monster-Girls");
            add("Name-The-Plague-Maiden-Mind");
            add("Nazi-M-F-Interracial");
            add("NTR-Superhero-M-F");
            add("Nun-Corruption-F-M");
            add("Occult-M-F-Size-Bondage");
            add("Piss");
            add("Pokemon-Milk");
            add("Pushing-Gaywards");
            add("Rape-Futa-Incest-F-F");
            add("Rape-Ghost-M-F-Sub");
            add("Rape-NTR-TF");
            add("Rape-Orc-Goblin-Loli-Size-F-M");
            add("Rape-Torture-F-M");
            add("Shota-Incest-M-F");
            add("Shota-Loli-Multi");
            add("Shota-Mother-Son-Incest-Slave");
            add("Size-F-M-Beast");
            add("Size-M-F");
            add("Size-Vore-F-F");
            add("Spyro-Dragon-Shota-M-M");
            add("Star-Trek-Barclay-Posting-Meme-Size-Smell");
            add("Sub-CBT-Degradation-Trap-Loli-M-F");
            add("TES-Argonian-Maid-Furry-M-F");
            add("TES-Elf-F-M-Porn-but-also-adventure");
            add("TES-Rape-F");
            add("TES-Rape-M");
            add("TF-Loli-F");
            add("Tiles-4chan-Meme-Degen-M");
            add("Touhou-Sub");
            add("Twin-Incest-M-F");
            add("Twin-M-F-Incest");
            add("Vampire-Loli");
            add("WH40K-Dom-Degen-Beast");
            add("X-COM-M-F-Furry");
            add("Zombie-Rape-M-F");
        }};
        m9.put("theme", "Just-Porn");
        m9.put("list", l9);

        Map<String, Object> m10 = new HashMap<>();
        List<String> l10 = new ArrayList<>(){{
            add("American-Psycho");
            add("Breaking-Bad");
            add("Dolemite-Is-My-Name");
            add("Good-Burger");
            add("Ishtar");
            add("It-is-a-rainy-night-when-you-r");
            add("James-Bond");
            add("Joker");
            add("Judge-Dred");
            add("Limmy-s-Show-Kill-Jester");
            add("Lord-of-the-Rings");
            add("Monster-Slayer");
            add("Shrek");
            add("Star-Wars-2");
            add("Star-Wars-3");
            add("Star-Wars-4");
            add("Star-Wars-5");
            add("Star-Wars-6");
            add("Star-Wars-Mandalorian");
            add("Star-Wars");
            add("The-Dark-Knight-2");
            add("The-Dark-Knight");
            add("Vampire");
            add("Warhammer-40k");
        }};
        m10.put("theme", "Movies-TV");
        m10.put("list", l10);

        Map<String, Object> m11 = new HashMap<>();
        List<String> l11 = new ArrayList<>(){{
            add("Dragons-Kobold-Piracy");
            add("Piracy-2");
            add("Piracy");
        }};
        m11.put("theme", "Ocean");
        m11.put("list", l11);

        Map<String, Object> m12 = new HashMap<>();
        List<String> l12 = new ArrayList<>(){{
            add("AI-proceeds-to-describe-a-long-backstory-Open-ended");
            add("Anons-have-said-this-provides-some-cool-battles");
            add("Go-full-Biblical-on-their-asses-Not-in-a-sexual-way-though-then-it-would-be-under-Just-Porn");
            add("Historic-RTS-Campaign");
        }};
        m12.put("theme", "Particularly-Interesting-or-Good");
        m12.put("list", l12);

        Map<String, Object> m13 = new HashMap<>();
        List<String> l13 = new ArrayList<>(){{
            add("2001-Space-Odyssey");
            add("Anon-Research-Zombie-Island");
            add("Anon-Robots-Maid");
            add("Body-Horror-Morality");
            add("Cyberpunk");
            add("Generic-Space-Piracy");
            add("Original-Cyborg");
            add("Original-Space-2");
            add("Original-Space-3");
            add("Original-Space");
            add("Post-Apocalypse-2");
            add("Post-Apocalypse");
            add("Post-apocalyptic-Soviet-Army");
            add("Space-Station-13-2");
            add("Space-Station-13-3");
            add("Space-Station-13-4");
            add("Space-Station-13");
            add("Stalker");
            add("Time-Travel-ISOT");
        }};
        m13.put("theme", "Space-Sci-fi");
        m13.put("list", l13);

        Map<String, Object> m14 = new HashMap<>();
        List<String> l14 = new ArrayList<>(){{
            add("4chan-Tower-Anon-Meta");
            add("Abstract-Lyrics");
            add("Amazon-Horror");
            add("Anon-Crypto-BOGGED");
            add("Anon-Love-Story-Natalia-Poklonskaya");
            add("Anon-Meta-AI-Vanilla");
            add("Anon-Meta-Open-ended");
            add("Anon-Meta");
            add("Anon-Romance-Christmas");
            add("Anon-Tendies");
            add("Anon-TTRPG-Meta-Magical-Realm");
            add("Art-Fetish");
            add("Based-Terry-God-s-Chosen-Rest-in-Peace");
            add("Bill-Nye-Greta-Thunberg-Crossover");
            add("Boomer");
            add("Buy-my-game");
            add("Catgirl-Lilly-Daughteru");
            add("Doughcat-Breadcat-Horror-Transformation");
            add("GamerGate-Feminism");
            add("Gordon-Ramsay-Cooking");
            add("Horror-Survival-Snow");
            add("How-can-he-keep-getting-away-with-it");
            add("It-s-summer-vacation-and-your");
            add("Lilly-Daughteru");
            add("Magical-Girl-2");
            add("Magical-Girl-3");
            add("Magical-Girl");
            add("Meta-4chan-0-10-Have-been-deposited-into-your-account");
            add("Meta-4chan");
            add("Meta-AI-2");
            add("Meta-AI-Anon-Retards");
            add("Meta-AI-Anon");
            add("Meta-AI");
            add("Meta-Twitch-Cancer-Modern");
            add("Meta-Twitch-EThot");
            add("Modern-Drama");
            add("Modern-Gang-Warfare");
            add("Modern-Silly-Walks");
            add("Original-Superhero-2");
            add("Original-Superhero");
            add("Original-Winter-Modern-Survival");
            add("Ozzy-and-Drix");
            add("Racism-Edgy-Shit-Moonman");
            add("SWAT-Modern-Action");
            add("Vietnam-Fantasy-Magic-Crossover");
            add("You-are-a-23-year-old-man-who");
            add("You-are-a-frogposter-from-4cha");
            add("You-are-a-student-at-a-Mormon");
            add("You-are-a-world-class-hitman");
            add("You-are-Geoff-Keighley-and-ton");
            add("You-are-Janny-a-moderator-fro");
            add("You-are-the-hacker-known-as-4c");
            add("You-have-been-captured-by-a-sa");
            add("You-turn-to-see-Sylvie-looking");
            add("Your-name-is-Jeffrey-Epstein");
            add("Your-name-is-Matthew-and-you");
        }};
        m14.put("theme", "Urban-Modern-Meta");
        m14.put("list", l14);

        Map<String, Object> m15 = new HashMap<>();
        List<String> l15 = new ArrayList<>(){{
            add("Alan-Watts-New-Age-Garbage-Lucid-Dreaming");
            add("Anon-Degenerate-Abortion");
            add("Anon-Faggot-OP");
            add("B-R-meme-pol");
            add("Faggot");
            add("Glug-Glug-Vore-Snuff-Feeding");
            add("Gore-Abuse");
            add("NIGGERS");
            add("Racism-Edgy-Shit-pol");
            add("Retardation-Abstract-Fetish");
            add("Star-Wars-7");
            add("Weird-Shit-Brapfags-should-be-executed");
            add("You-are-the-admin-of-Kiwifarms");
        }};
        m15.put("theme", "Weird-Retarded");
        m15.put("list", l15);

        maps.add(m1);
        maps.add(m2);
        maps.add(m3);
        maps.add(m4);
        maps.add(m5);
        maps.add(m6);
        maps.add(m7);
        maps.add(m8);
        maps.add(m9);
        maps.add(m10);
        maps.add(m11);
        maps.add(m12);
        maps.add(m13);
        maps.add(m14);
        maps.add(m15);
    }
}
